version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2
        environment:
          WORDPRESS_DB_HOST: 127.0.0.1:3306
          WORDPRESS_DB_NAME: wordpress_test
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: ""
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - run:
          name: Install PHP Extensions and MySQL Client
          command: |
            sudo apt-get update && sudo apt-get install subversion\
              default-mysql-client         
      - run:
          name: Create WordPress Test Database
          command: |
            mysql -h 127.0.0.1 -uroot -e 'CREATE DATABASE wordpress_test;'
      - run:
          name: Install PHPUnit Polyfills
          command: |
            composer require --dev phpunit/phpunit ^9
      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-interaction
      - run:
          name: Install WordPress test suite
          command: |
            echo 'y' | bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
      - run:
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
