version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
        environment:
          WORDPRESS_DB_HOST: 127.0.0.1:3306
          WORDPRESS_DB_NAME: wordpress_test
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: ""
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - run:
          name: Install PHP Extensions and MySQL Client
          command: |
            sudo apt-get update && sudo apt-get install -y \
              libpng-dev \
              libpng-tools \
              default-mysql-client
            docker-php-ext-install gd
      - run:
          name: Create WordPress Test Database
          command: |
            mysql -h 127.0.0.1 -uroot -e 'CREATE DATABASE wordpress_test;'
      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-interaction
      - run:
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
